### ISSUE TITLE
createadmin user generates error 'django.db.utils.OperationalError: no such table: auth_user'

### ISSUE THREAD

**Issue by arademaker** [gklyne/annalist#43]
I am running from the docker inside Ubuntu:

```
# annalist-manager createadminuser
INFO:annalist.apps:Annalist version 0.1.22 (development configuration)
INFO:annalist.apps:SETTINGS_MODULE:  annalist_site.settings.devel
INFO:annalist.apps:BASE_DATA_DIR:    /usr/local/lib/python2.7/dist-packages/annalist_root/devel
INFO:annalist.apps:CONFIG_BASE:      /annalist_site/.annalist/
INFO:annalist.apps:DJANGO_ROOT:      /usr/local/lib/python2.7/dist-packages/django
INFO:annalist.apps:SITE_CONFIG_DIR:  /usr/local/lib/python2.7/dist-packages/annalist_root/annalist_site
INFO:annalist.apps:SITE_SRC_ROOT:    /usr/local/lib/python2.7/dist-packages/annalist_root
INFO:annalist.apps:STATICFILES_DIRS: /usr/local/lib/python2.7/dist-packages/annalist_root/annalist/static/
INFO:annalist.apps:DB PATH:          /usr/local/lib/python2.7/dist-packages/annalist_root/db.sqlite3
INFO:annalist.apps:ALLOWED_HOSTS:    
INFO:annalist.apps:LOGGING_FILE:     None (output to console)
Admin user name:        admin
Traceback (most recent call last):
  File "/usr/local/bin/annalist-manager", line 9, in <module>
    load_entry_point('Annalist==0.1.22', 'console_scripts', 'annalist-manager')()
  File "/usr/local/lib/python2.7/dist-packages/annalist_root/annalist_manager/am_main.py", line 180, in runMain
    return runCommand(userhome, userconfig, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/annalist_root/annalist_manager/am_main.py", line 169, in runCommand
    status   = run(userhome, userconfig, options, progname)
  File "/usr/local/lib/python2.7/dist-packages/annalist_root/annalist_manager/am_main.py", line 120, in run
    return am_createadminuser(annroot, userhome, options)
  File "/usr/local/lib/python2.7/dist-packages/annalist_root/annalist_manager/am_createuser.py", line 177, in am_createadminuser
    if User.objects.filter(username=user_name):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 145, in __nonzero__
    self._fetch_all()
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 966, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 265, in iterator
    for row in compiler.results_iter():
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 700, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 81, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/sqlite3/base.py", line 485, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: auth_user
root@3fce21e26d9d:/# 
```

**Comment by gklyne** [comment]
@ arademaker - thanks for the report.  

I *think* this is a bug that was fixed in release 0.1.24:

    BUG (from 0.1.22 release): creating admin user in new site fails
        - https://github.com/gklyne/annalist/blob/master/documents/release-notes/release-v0.1.md

In my rush to push out V0.1.24 I think I forgot to update the Docker images.  Doing that now.  I'll post an update here when it's done.

(Alternatively, I personally find the installation without Docker - using Python virtualenv and pip - is pretty much as easy as using Docker, but YMMV.)

**Comment by arademaker** [comment]
> (Alternatively, I personally find the installation without Docker - using Python virtualenv and pip - is pretty much as easy as using Docker, but YMMV.)
> 
I will give it a try. Thanks.

**Comment by gklyne** [comment]
I've now updated the docker images and all seems to be working (for me):

    (anenv)graham@dev-annalist-50gb:~/github/gklyne/annalist/src/docker/annalist$ docker run --interactive --tty --rm     --volumes-from=annalist_site     gklyne/annalist bash
    root@02f99bc290d7:/# annalist-manager version
    0.1.24b
    root@02f99bc290d7:/# annalist-manager defaultadminuser
    Creating user admin
    User admin already exists

I'll leave this issue open for a day or so, and if I hear no more I'll close it.

**Comment by gklyne** [comment]
On reflection, I realized I needed to also test with a new (blank) annalist_site container, which I've now done:

    root@7ec7affad09e:/# annalist-manager createsitedata
    Initializing Annalist site in /annalist_site/annalist_site
    Copy Annalist site data
    from /usr/local/lib/python2.7/dist-packages/annalist_root/annalist/data/sitedata
    - types -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - lists -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - views -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - groups -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - fields -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - vocabs -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - users -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    - enums -> /annalist_site/annalist_site/c/_annalist_site/_annalist_collection
    Generating /annalist_site/annalist_site/c/_annalist_site/_annalist_collection/coll_context.jsonld
    Now run 'annalist-manager initialize' to create site admin database
    root@7ec7affad09e:/# annalist-manager initialize
    INFO:annalist_site.settings.personal:Annalist version 0.1.24b (personal configuration)
    Operations to perform:
      Synchronize unmigrated apps: oauth2, annalist
      Apply all migrations: admin, contenttypes, auth, sessions
    Synchronizing apps without migrations:
      Creating tables...
        Creating table oauth2_credentialsmodel
      Installing custom SQL...
      Installing indexes...
    Running migrations:
      Applying contenttypes.0001_initial... OK
      Applying auth.0001_initial... OK
      Applying admin.0001_initial... OK
      Applying sessions.0001_initial... OK
    root@7ec7affad09e:/#
    root@7ec7affad09e:/#
    root@7ec7affad09e:/# annalist-manager defaultadminuser
    Creating user admin
    Password:
    Re-enter password:
    root@7ec7affad09e:/#

All seems well, so I'm closing the issue now.
