### ISSUE TITLE
openid connect Server Error (500)

### ISSUE THREAD

**Issue by ranvijay-zymr** [gklyne/annalist#44]
Request URL:http://localhost:8000/annalist/login_done/?state=P5L-vLeiKCJcLSn5-OpK1zoxNDgxMDA2NTA2&code=4/4nz4vfkKdY-gqB0xpJAOXzV4XaymX3rcJzQwOquA_1c&authuser=0&hd=zymr.com&session_state=a06cbf8e7e7256806e37b5bce6ede1ce254f8f65..39ae&prompt=consent
Request Method:GET
Status Code:500 INTERNAL SERVER ERROR
Remote Address:127.0.0.1:8000
Response Headers
view source
Content-Type:text/html
Date:Tue, 06 Dec 2016 06:42:30 GMT
Server:WSGIServer/0.1 Python/2.7.10
Vary:Cookie
X-Frame-Options:SAMEORIGIN
Request Headers
view source
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8
Cache-Control:max-age=0
Connection:keep-alive
Cookie:csrftoken=U9fQzrrP2dFBfKtDjkSStFgWdHkKjcRd; sessionid=y7fk75jl8bf4fy4b844403f1jr4z7dzf
Host:localhost:8000
Upgrade-Insecure-Requests:1
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.98 Safari/537.36
Query String Parameters
view source
view URL encoded
state:P5L-vLeiKCJcLSn5-OpK1zoxNDgxMDA2NTA2
code:4/4nz4vfkKdY-gqB0xpJAOXzV4XaymX3rcJzQwOquA_1c
authuser:0
hd:zymr.com
session_state:a06cbf8e7e7256806e37b5bce6ede1ce254f8f65..39ae
prompt:consent

<img width="1280" alt="screen shot 2016-12-06 at 12 15 38 pm" src="https://cloud.githubusercontent.com/assets/21329381/20915765/c926943e-bbad-11e6-8c79-52167e7c0a9b.png">

**Comment by gklyne** [comment]
Does the server log offer any clues?

(To view the log, use a console, activate the python virtual environment and try this command)

    less $(annalist-manager serverlog)

(I'm assuming a BASH shell under OSX)

#g

**Comment by gklyne** [comment]
(BTW, it appears the error is appearing on the redirect back from the OpenID Connect authorization.)

**Comment by ranvijay-zymr** [comment]
KeyError: 'profile_uri'
ERROR 2016-12-06 07:28:14,514 Internal Server Error: /annalist/login_done/
Traceback (most recent call last):
  File "/Users/ranvijay.s/annenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/ranvijay.s/annenv/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/ranvijay.s/annenv/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/ranvijay.s/annenv/lib/python2.7/site-packages/annalist_root/login/auth_oidc_client.py", line 115, in get
    profile_uri=provider_details['profile_uri']
KeyError: 'profile_uri'

**Comment by ranvijay-zymr** [comment]
Sorry my fault I have not changed/add https://github.com/gklyne/annalist/blob/master/documents/openid-connect-setup.md
